import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/layouts'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} fx-center fx-column`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
